build_from:
  amd64: "ghcr.io/home-assistant/amd64-base:3.19"
  armv7: "ghcr.io/home-assistant/armv7-base:3.19"
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.19"
labels:
  org.opencontainers.image.title: "Bark Server"
  org.opencontainers.image.description: "自建 Bark 推送服务器"
  org.opencontainers.image.source: "https://github.com/Finb/bark-server"
