name: "Sun-Panel 定制面板"
version: "1.0"
slug: "sun_panel_dd"
description: "一个漂亮的个人首页，数据已重定向至 HAOS /data 目录"
arch:
  - amd64
  - aarch64
startup: application
boot: auto

# 🎯 资源配额：限制内存和 CPU，防止“啃食”宿主机
cpu: 0.5
memory: 512

image: "crpi-xp12t4ileyfuxc1m.cn-hongkong.personal.cr.aliyuncs.com/jjss520/sun-panel-dd"

ports:
  "3002/tcp": 3002

map:
  - share:rw
  - config:rw

environment:
  TZ: "Asia/Shanghai"
