name: "Sun-Panel (原生适配版)"
version: "v1.3.5"
slug: "sun_panel_dd"
description: "Sun-Panel v1.3.5，镜像原生读写 /data 目录，完美适配 HAOS。"
arch:
  - amd64
  - aarch64
startup: application
boot: auto

# 🎯 资源配额：依然加上限制，防止日后失控
cpu: 0.5
memory: 512

# 🎯 直接指向你的远程镜像库
image: "ghcr.io/jjss520/sun-panel-dd"

ports:
  "3002/tcp": 3002

map:
  - share:rw
  - config:rw

environment:
  TZ: "Asia/Shanghai"
